[package]
name = "ca.rs"
version = "0.1.0"
authors = ["Peter Jacobs <peter@crespyl.net>"]

[[bin]]
name = "ca"
path = "src/ca.rs"

[dependencies]
rand = "*"
bit-vec = "0.4"

docopt = "0.8"

serde = "1.0"
serde_derive = "1.0"
